report:
  out_dir: ./report   # allure html 输出路径

session:      # 接口session
  base_url: "http://47.103.198.253"
  time_out: 4

mocks:         # 接口mock
  -           # 每个mock规则使用   - 进行分隔
    request:  # 要匹配的request
      method: GET
      url: https://mock.google.com
    response: # mock的response
      status_code: 200
      headers:
        create_by: mocker
      json:
        code: 1
        msg: hello
  -
    request:  # 要匹配的request
      method: GET
      url: https://mock.baidu.com
    response: # mock的response
      status_code: 200
      headers:
        create_by: mocker
      json:
        code: 2
        msg: hello

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    formatter: # 日志格式：等级-时间-模块-内容
      format: '%(levelname)-8s %(asctime)s [%(name)s]  : %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: formatter
      level: DEBUG
    file:
      class: logging.handlers.TimedRotatingFileHandler # 基于日期分割日志
      encoding: utf-8
      filename: ./logs/my_test.log
      when: midnight
      backupCount: 10
      formatter: formatter
      level: DEBUG
  
  loggers:
    "":
      handlers:
        - file
      level: INFO
