---
version: 1
disable_existing_loggers: false
formatters:
  formatter: # 日志格式：等级-时间-模块-内容
    format: '%(levelname)-8s %(asctime)s [%(name)s]  : %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: formatter
    level: DEBUG
  file:
    class: logging.handlers.TimedRotatingFileHandler
    encoding: utf-8
    filename: ./logs/my_test.log
    when: midnight
    backupCount: 10
    formatter: formatter
    level: INFO

loggers:
  "":
    handlers:
      - file
    level: DEBUG
